pancakeswap/pancake-uikit

- src/components/Button/Button.tsx
- src/components/Button/IconButton.tsx
- src/components/Button/index.stories.tsx
- src/components/Button/index.tsx
- src/components/ButtonMenu/ButtonMenuItem.tsx
- src/index.ts
- src/widgets/Modal/Modal.tsx
- src/widgets/Nav/Buttons.tsx
- src/widgets/Nav/Panel.tsx
- src/widgets/Nav/UserBlock.tsx
- src/widgets/WalletModal/AccountModal.tsx
- src/widgets/WalletModal/WalletCard.tsx
> feat(button): Icon button

- src/components/Dropdown/index.stories.tsx
- src/components/Progress/index.stories.tsx
- src/widgets/Modal/index.stories.tsx
- src/widgets/WalletModal/index.stories.tsx
Change import locations of 'button' across WalletModal, Modal, Dropdown & Progress stories
> Fix /Button component imports

- src/theme/dark.ts
- src/theme/index.ts
- src/theme/light.ts
- src/widgets/Modal/Modal.tsx
- src/widgets/Modal/theme.ts
- src/widgets/Modal/types.ts
> fix(modal): Dark mode

- src/components/Input/index.stories.tsx
- src/components/Input/index.tsx
- src/components/Input/types.ts
- src/index.ts
Added additional sizes so they align with our buttons.
Closes #78
> feat: Input

- src/components/Progress/StyledProgress.tsx
> fix(progress): Issue when progress is 0 or 100%

- src/__tests__/components/button.test.tsx
- src/components/Button/StyledButton.tsx
> fix(button): Line height

- src/components/Button/theme.ts
- src/components/Button/types.ts
> feat(button): Success variant

- src/index.ts
- src/widgets/Footer/index.tsx
- src/widgets/Modal/Modal.tsx
- src/widgets/Modal/ModalContext.tsx
- src/widgets/Modal/index.tsx
- src/widgets/Modal/types.ts
- src/widgets/Nav/Panel.tsx
- src/widgets/Nav/UserBlock.tsx
- src/widgets/Nav/index.tsx
- src/widgets/WalletModal/index.stories.tsx
- src/widgets/WalletModal/index.tsx
- src/widgets/WalletModal/useWalletModal.tsx
> fix: Tweak kit for exchange integration

- src/__tests__/components/buttonmenu.test.tsx
- src/components/ButtonMenu/ButtonMenu.tsx
- src/components/ButtonMenu/ButtonMenuItem.tsx
- src/components/ButtonMenu/StyledButtonMenu.tsx
- src/components/ButtonMenu/index.stories.tsx
- Using `as` was not forwarding the component properly
> fix(buttonmenu): "as" not being forwarded correctly

- src/widgets/Menu/Logo.tsx
- src/widgets/Menu/Menu.tsx
- src/widgets/Menu/types.ts
Going to mark this as a temporary solution. Addresses https://github.com/pancakeswap/pancake-swap-interface/issues/119
> feat(menu): Add prop to make logo absolute url

- src/__tests__/components/buttonmenu.test.tsx
- src/components/ButtonMenu/ButtonMenu.tsx
- src/components/ButtonMenu/ButtonMenuItem.tsx
- src/components/ButtonMenu/StyledButtonMenu.tsx
> style(buttonmenu): Updated subtle variant

- src/__tests__/components/alert.test.tsx
- src/__tests__/components/heading.test.tsx
- src/__tests__/components/link.test.tsx
- src/__tests__/components/text.test.tsx
- src/__tests__/widgets/modal.test.tsx
- src/__tests__/widgets/walletModal.test.tsx
- src/components/Svg/Icons/Minus.tsx
- src/components/Svg/index.tsx
- src/components/Text/Text.tsx
- src/components/Text/index.stories.tsx
- src/components/Text/types.ts
- Added `Minus` svg icon for new farm card 'withdraw' button
- Added `textTransform` prop to text to allow for it to receive a textTransform argument (i.e. 'uppercase' for the new card text)
> Updates for new version of farm card

- src/__tests__/components/breadcrumbs.test.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Breadcrumbs/index.stories.tsx
- src/components/Breadcrumbs/index.tsx
- src/components/Breadcrumbs/types.ts
- src/components/Svg/Icons/ChevronRight.tsx
- src/components/Svg/index.tsx
- src/index.ts
> feat: Breadcrumbs

- src/__tests__/components/spinner.test.tsx
- src/components/Spinner/Spinner.tsx
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-uikit/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does
> fix: Update Spinner

- src/widgets/Toast/Toast.tsx
- src/widgets/Toast/ToastContainer.tsx
- src/widgets/Toast/index.stories.tsx
- src/widgets/Toast/index.tsx
- src/widgets/Toast/types.ts
Renamed confusing props and added missing types
> refactor(toast): Updated prop & type names

- src/__tests__/components/card.test.tsx
- src/components/Card/StyledCard.tsx
- src/components/Card/index.stories.tsx
- src/components/Card/types.ts
We had the typings for the space props without the space!
> fix(card): Space props

- src/__tests__/components/radio.test.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Radio/Radio.tsx
- src/components/Radio/types.ts
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-uikit/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does
> fix: Radio and Breadcrumb

- src/components/Svg/Icons/Calculate.tsx
- src/components/Svg/index.tsx
- Added calculate icon to SVGs for use in APY calculator modal button
> Added calculate icon svg

- src/__tests__/components/alert.test.tsx
- src/components/Alert/Alert.tsx
- src/components/Alert/index.stories.tsx
Fixed issue where the styles were off when the title breaks.
> fix(alert): Spacing

- src/__tests__/components/breadcrumbs.test.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Breadcrumbs/index.stories.tsx
- src/components/Breadcrumbs/types.ts
- Breadcrumbs now wrap on mobile
- Added space props to the typing
> feat(breadcrumbs): Add mobile stylings

- .eslintrc
- src/components/Radio/index.stories.tsx
- src/widgets/Menu/Menu.tsx
Fix the glitchy behaviour of the menu on scroll
fix #132
> fix: Menu hide logic

- src/widgets/Modal/Modal.tsx
- src/widgets/Modal/ModalContext.tsx
- src/widgets/Modal/index.stories.tsx
- src/widgets/Modal/index.tsx
- src/widgets/Modal/types.ts
- src/widgets/Modal/useModal.ts
> feat(modal): Add option to disable overlay click

- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/Avatar.tsx
- src/widgets/Menu/Menu.tsx
- src/widgets/Menu/icons/NoProfileAvatar.tsx
- src/widgets/Menu/index.stories.tsx
- src/widgets/Menu/types.ts
> feat(menu): Profile avatar

- src/__tests__/widgets/menu.test.tsx
- src/__tests__/widgets/walletModal.test.tsx
- src/components/Svg/Icons/Copy.tsx
- src/components/Svg/index.tsx
- src/components/Text/Text.tsx
- src/components/Text/index.stories.tsx
- src/components/Text/types.ts
- src/widgets/WalletModal/AccountModal.tsx
- src/widgets/WalletModal/CopyToClipboard.tsx
- src/widgets/WalletModal/index.stories.tsx
> feat: Add copy to clipboard on the address

- src/__tests__/components/alert.test.tsx
- src/components/Alert/Alert.tsx
- src/components/Alert/index.stories.tsx
- src/components/Alert/types.ts
- src/widgets/Toast/Toast.tsx
- src/widgets/Toast/ToastAction.tsx
- src/widgets/Toast/index.stories.tsx
- src/widgets/Toast/types.ts
- Moves `Alert` component's `description` prop to children
- Add ability to specify a toast action
> feat(toasts): Add ability to add action

- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/Avatar.tsx
- src/widgets/Menu/types.ts
> feat(menu): Add pip to profiles without images

- src/__tests__/widgets/walletModal.test.tsx
- src/widgets/WalletModal/AccountModal.tsx
- src/widgets/WalletModal/CopyToClipboard.tsx
- src/widgets/WalletModal/useWalletModal.tsx
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-uikit/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does
> fix: Copy to clipboard format

- src/__tests__/components/heading.test.tsx
- src/__tests__/widgets/modal.test.tsx
- src/__tests__/widgets/walletModal.test.tsx
- src/components/Heading/Heading.tsx
> style(heading): Add mobile sizes for large headers

- src/__tests__/components/toggle.test.tsx
- src/components/Toggle/StyledToggle.tsx
- src/components/Toggle/Toggle.tsx
- src/components/Toggle/index.stories.tsx
- src/components/Toggle/index.tsx
- src/components/Toggle/types.ts
changed checked color from 'success' to 'secondary'
> style: Add scale property to Toggle component

- src/components/Toggle/StyledToggle.tsx
- src/components/Toggle/Toggle.tsx
- src/components/Toggle/types.ts
> fix(toggle): Types

- src/components/Heading/types.ts
> fix(heading): Sizes type was wrong

- package.json
bump react-dom to 17.x to fix react mismatch error in pancake-frontend
> fix: bump react-dom to 17.x to fix react mismatch error in pancake-frontend

- src/__tests__/components/alert.test.tsx
- src/__tests__/components/heading.test.tsx
- src/__tests__/components/link.test.tsx
- src/__tests__/components/text.test.tsx
- src/__tests__/widgets/modal.test.tsx
- src/__tests__/widgets/walletModal.test.tsx
- src/components/Text/Text.tsx
- src/components/Text/index.stories.tsx
- src/components/Text/types.ts
Add typography props on `Text` component
> feat: Add typography props to Text

- src/__tests__/widgets/menu.test.tsx
- src/widgets/Menu/MenuEntry.tsx
> style: Remove bold from rainbow callout

- .github/workflows/lint.yml
> build: Commit lint test

- src/widgets/WalletModal/AccountModal.tsx
- src/widgets/WalletModal/WalletCard.tsx
- src/widgets/WalletModal/config.tsx
- src/widgets/WalletModal/index.tsx
- src/widgets/WalletModal/types.ts
Save connector id in the localstorage.
this is a breaking change.
> chore: Save the connector id in localstorage

- src/widgets/Menu/components/MenuEntry.tsx
- src/widgets/Menu/components/MenuLink.tsx
[ ] Before opening a pull request, please read the [contributing guidelines](https://github.com/pancakeswap/pancake-uikit/blob/master/CONTRIBUTING.md) first
[ ] If your PR is work in progress, open it as `draft`
[ ] Before requesting a review, all the checks need to pass
[ ] Explain what your PR does
> fix: Re render on mobile

- src/components/Button/Button.tsx
> feat(button): Add current color to start/end icons

- src/__tests__/components/tag.test.tsx
- src/components/Tag/StyledTag.tsx
- src/components/Tag/Tag.tsx
- src/components/Tag/index.stories.tsx
- src/components/Tag/index.tsx
- src/components/Tag/theme.ts
- src/components/Tag/types.ts
- Refactored Tag component to use variant
> refactor(tag): Add variant to tag

- src/__tests__/components/notificationdot.test.tsx
- src/components/NotificationDot/NotificationDot.tsx
> refactor: Adjust border on dot

- netlify.toml
> build: Add Netlify TOML
